# Generated by Django 3.2 on 2021-04-22 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_auto_20210422_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctypes',
            new_name='Doctype',
        ),
    ]
