# Generated by Django 3.2 on 2021-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_doctypes_doctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=64, verbose_name='Last')),
                ('firstname', models.CharField(max_length=64, verbose_name='First')),
                ('middlename', models.CharField(max_length=64, verbose_name='Middle')),
                ('clocknumber', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['lastname', 'firstname', 'middlename'],
            },
        ),
    ]
